### ISSUE TITLE
anko version required

### ISSUE THREAD

**Issue by chyroc** [mattn/play-anko.appspot.com#1]
commit / tag

**Comment by mattn** [comment]
What do you mean version?  runtime.Version?

https://play-anko.appspot.com/p/8a40f2a83e042c69017288574683916164640f0d

**Comment by chyroc** [comment]
no, mean anko commit version ,such as :

8ba6b1ae5233dce89616922dae05b07efbf3dd7c 

for

https://github.com/mattn/anko/commit/8ba6b1ae5233dce89616922dae05b07efbf3dd7c

**Comment by mattn** [comment]
done https://github.com/mattn/play-anko.appspot.com/commit/6bf5cea45488fa8d2769ef51a7099491a85b7f23
